spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/datajpa
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
      # application 로딩 시점에 drop 후 create
    properties:
      hibernate:
  #      show_sql: true # jpa가 실행하는 쿼리를 콘솔에 출력
        format_sql: true
logging.level:
  org.hibernate.SQL: debug # 로그로 남김
  #  org.hibernate.type: trace